### ISSUE TITLE
Start learning section part two

### ISSUE THREAD

**Issue by farishkash** [mkotajny/CA5_ColmarAcademy#2]
The goal in this section is to keep the divs as two rows with three columns each.  If you did this project on a low resolution screen such as what is on a laptop, you would have not noticed this.  You can control this by adjusting the width.

![colmar_academy](https://user-images.githubusercontent.com/5844161/34636185-e989d6de-f250-11e7-8e33-ec5435ba458e.png)

**Comment by mkotajny** [comment]
Yeah :). My guess was different - that 2 rows and 3 columns was on specification image - but items should be flexible and wrap dependently on screen resolution. But now, I understand your point.
